### ISSUE TITLE
Can you optimize this for .Net Framework v4.0

### ISSUE THREAD

**Issue by username1565** [otuncelli/f5-steganography#3]
This program cann't be compiled for win32, and not supporting Windows XP.
Latest .NET framework for Windows XP is v4.0.
That means this program not have backward compatibility with old versions Windows,
and code is not [portable](https://username1565.github.io/js-jpeg-steg/).

**Comment by otuncelli** [comment]
It's already targeting .NET Framework v4.0.

**Comment by username1565** [comment]
@otuncelli, I did try to compile this on windows XP, using .NET Framework v4.0.30319:
```
disk:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe /property:Configuration=Release F5-Steganography.sln
```
But I see 4 warnings and 9 errors.
Maybe, this library can working for win32, if this errors will be fixed.
Do you have compiled portable exe for win32?
Can you publish this in "releases"?

I just want to get working f5-algorithm, which can be compiled for win32
and this algorithm will be better to be in one cs-file (C#),
without any libraries, to be included [here](https://github.com/username1565/nanoboard)
This nanoboard working only with PNG-files.
I also, have JavaScript implementation of f5-js-jpeg-steg, [here](http://username1565.github.io/js-jpeg-steg/), and, as you can see, this is [only in one JS-file](https://github.com/username1565/js-jpeg-steg/blob/master/index_files/js/jsf5steg.js).
but I don't know how to translate this all to C# programming language.

**Comment by otuncelli** [comment]
It could be the C# language version causing the errors not the framework version. Because it's already targeting .NET 4.0. C# 4.0 or newer should compile without any problems (both x64 and x86 compile fine for me).

Since i don't own the algorithm and not maintaining the code anymore, I can't provide a release. This is just a direct port from the java version, not the javascript version. I don't know anything about javascript.

Yes, technically it's possible to put all the code in a single Program.cs file as long as objects are in their correct namespace. Though it would still have BouncyCastle dependency unless you do something about it.

**Comment by username1565** [comment]
Ok. Got it. I did download nupkg-packages and add this to my fork in master-branch.
Compilation successfully. Lite version you can see in the second branch.
Pull request opened.
